// vue-lenis/src/components/SectionTwo.vue
<template>
    <div class="bg-[green] text-white h-screen w-full flex flex-col items-center justify-center" id="sectionTwo">
        <h1>Section Two</h1>

        <div class="flex gap-2">
            <div class="box w-[10rem] h-[10rem] bg-[blue] my-4"> </div>

<div class="box1 w-[10rem] h-[10rem] bg-[red] my-4"> </div>



<div class="box2 w-[10rem] h-[10rem] bg-[teal] my-4"> </div>
        </div>
     

        <div class="flex gap-4 w-full box-container2">
            <div class="box3 w-[10rem] h-[10rem] bg-[purple] my-4"> </div>


<div class="box4 w-[10rem] h-[10rem] bg-[pink] my-4"> </div>

<div class="box5 w-[10rem] h-[10rem] bg-[black] my-4"> </div>
        </div>
       
    </div>
</template>

<script setup lang="ts">

import { gsap } from 'gsap';
import ScrollTrigger from 'gsap/ScrollTrigger';
import { onMounted } from 'vue';
gsap.registerPlugin(ScrollTrigger)


onMounted(() => {
let tl = gsap.timeline({
    scrollTrigger:{
        trigger:'#sectionTwo',
        start: 'top center',
            end:'top +=50',
            markers:true,
            scrub:true
    }
})

tl.from('.box', {
    opacity:0,
    ease:"power4.inOut",
    duration:1.2,
    y:200
})

tl.from('.box3', {
    opacity:0,
    // y:200,
    stagger:0.4,
    ease:"power3.inOut"
})
tl.from('.box4', {
    opacity:0,
    // y:200,
    stagger:0.6,
    ease:"power3.inOut"
})

tl.from('.box5', {
    opacity:0,
    // y:200,
    stagger:0.8,
    ease:"power3.inOut"
})
})



</script>

<style scoped>

</style>

// react-tailwind/src/components/SectionTwo.tsx
import React, { useEffect } from 'react'
import gsap from 'gsap'
import ScrollTrigger from 'gsap'
gsap.registerPlugin(ScrollTrigger)


const SectionTwo = () => {
  useEffect(() => {
    // console.log('current',pageRef.current)
    const ctx = gsap.context(() => {
    const sectionTwoTl = gsap.timeline({
      scrollTrigger: {
        trigger:'#sectionTwo' ,
        start: "top center",
      end: "top +=10",
      // markers:true,
      scrub: 0.7,
      },
    })
     sectionTwoTl.to('#sectionTwo', {
      backgroundColor: 'purple',
      duration:1.2,
      color:'white',
      ease:"power4.inOut"
    }).fromTo('.title',{opacity:0},{ y: 0, opacity: 1, duration:1.5, clipPath: "polygon(0 100%, 100% 100%, 100% 0, 0 0)" },'<0.1')
    .from('.box1',{y:200,opacity:0,ease:"power3.inOut",duration:1.2})

    sectionTwoTl.fromTo('#box',{opacity:0},{ y: 0, opacity: 1, duration:1.5, clipPath: "polygon(0 100%, 100% 100%, 100% 0, 0 0)", ease:"power3.inOut" },'<0.1')

    return () => ctx.revert();

    
  })
  })


  return (
    <div className='h-screen bg-[orange] text-5xl w-full flex items-center justify-center' id="sectionTwo">SectionTwo
    
    <div className='box w-[10rem] h-[10rem] mx-auto bg-[blue]' id='box'></div>
    </div>
  )
}

export default SectionTwo
